### ISSUE TITLE
Please create new java class related with connections

### ISSUE THREAD

**Issue by fuss86** [RobRaimo/Neo4j-Wlodkowic#1]
https://github.com/RobRaimo/Neo4j-Wlodkowic/blob/df73911d6e5fb8164ee86f0d0e052f0ab53683cd/JavaJApp_JDBC_ClientGUI/src/MainFrame.java#L925

Ref.
https://docs.oracle.com/javase/tutorial/java/javaOO/classvars.html
https://docs.oracle.com/javase/tutorial/java/javaOO/methods.html

**Comment by RobRaimo** [comment]
Hello Przemek, I really like your analysis.. because put me on the right
prospective of good coding.



The evidence of the fact is that I feel to be underleveled for this
programing task, so is really difficult for me complete your request
without before fill the theory gap that i have. Fill the gap will take for
sure more than a month of work. As we are running out time, could we find a
right compromise in order to complete this practice? I mean, for this next
5th semester is planned another practice task. If you like the idea, we
could divide and extend this task to the next practice too. In this way we
could better focus on programming for futher other 120h. Those are just my
though, i would talk you about during our next meeting.


The proposition for this practice is that you could draw the code
corrections, suggest and explain the right syntax to apply and I could
write in GIT the suggested corrections, rewriting the proper code in to the
final netbeans project. In this optic, 20 hours could be enough and we
could complete the practice session for this month.



Returning to the task, I send you an anticipation for Thursday in order
that you could take vision of my actual level and decide about. I have
updated the GIT but at the moment not all the code because before make
corrections, I would discuss with you the choices.


#1 Please create new java class related with connections
understand what you mean, but here i have problem doing without explained
example.. i could create a class, but i dont know how to return the output
serializzation

#2 Please create the serialization of nodes
same as the point 1

#3 Strings comparison is bad here. Don't compare objects - compare values.
if ( jcbSelCreateRelation.getSelectedItem().toString().equals("ENGAGED_IN")
) {

#4 Please create a validator classes that validates the relations and
incorporate it in the code
mm.. no idea..

#5 Advanced queries
once defined serializzation will be easy to manage this query request,

#6 vrCQL doesn't have to be a "global" field - stick wth local variables
delete the row
22 String vrCQL = null;
and declare inside the each subclass, foe ex. :
String  vrCQL = "MATCH (n) RETURN n LIMIT " + jtfMatchLimitN.getText();

#7 Please try to close resources using the try-with-resources Statement
understand what you mean, but here i have problem doing without explained
example

hank you for your understanding, Posdrawiam
Roberto

2017-09-07 20:53 GMT+02:00 Przemyslaw Fusik <notifications@github.com>:

**Comment by RobRaimo** [comment]
in MainForm.java we create instance and methods of connctor class
    private void tnRDReadANodeActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        String vrCQL = "MATCH (n) RETURN n LIMIT " + jtfMatchLimitN.getText();
        jtaTextfield.setText(vrCQL + "\n\n");
        try {
            DBConnector_JDBC DBConJDBC = new DBConnector_JDBC();
            DBConJDBC.execute(vrCQL);
            //Connection(vrCQL);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            jtaTextfield.append("Exception catched...\n" + ex.toString());
        }
    }

thath are contained in aother class file DBConnector_JDBC.java
public class DBConnector_JDBC {
    
    public void execute(String queryCQL) throws SQLException {
        Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
        setCursor(hourglassCursor);
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;
        // Connect
        try {
            con = DriverManager.getConnection("jdbc:neo4j:bolt://localhost", "neo4j", "password");
            stmt = con.createStatement();
            rs = stmt.executeQuery(queryCQL);
            while (rs.next()) {
                jtaTextfield.append(rs.getString("n")+ "\n");
            }
        } catch(SQLException ex) {
            jtaTextfield.append("Exception catched...\n" + ex.toString());
            Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
            setCursor(normalCursor);
        } finally {
            con.close();
            stmt.close();
            rs.close();
        }
        Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        setCursor(normalCursor);
    }
}

**Comment by fuss86** [comment]
Please remove the `private void Connection(String vrCQL) throws SQLException` method from `MainFrame.java` and replace all calls to this method with an invocation of some instance of `DBConnector_JDBC` class

**Comment by fuss86** [comment]
Please also use the try-with-resources Statement (see https://github.com/RobRaimo/Neo4j-Wlodkowic/issues/7) from the `DBConnector_JDBC` class

**Comment by RobRaimo** [comment]
ok for tomorro! i will be there!.. master committed! :)

2017-09-20 22:04 GMT+02:00 Przemyslaw Fusik <notifications@github.com>:

**Comment by fuss86** [comment]
public static Connection getConnection() throws Exception {
        return DriverManager.getConnection(urlString, userName, passWord);
}

**Comment by RobRaimo** [comment]
The external class is rewritten as below:
```
public class DbConnectorJdbc {

    private static String urlString = "jdbc:neo4j:bolt://localhost"; 
    private static String userName = "neo4j";   
    private static String passWord = "password";

    public static Connection getConnection() throws Exception {
        return DriverManager.getConnection(urlString, userName, passWord);
    }
}
```
and in the MainForm is used now as method with instance invocation instead of a object creation

```
  private void tryJdbcConnection(String vrCQL) throws SQLException{
        hourglassCursor();
        try (Connection con = DbConnectorJdbc.getConnection();
             Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery(vrCQL); ){
            while (rs.next()) {
                jtaTextfield.append(rs.getString("n")+ "\n");
            }
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(
                    null,
                    "Database connection error.\n\n" + ex.toString(),
                    "error",
                    JOptionPane.ERROR_MESSAGE
            );
            //jtaTextfield.append("Exception catched...\n" + ex.toString());
        } finally {
        normalCursor();
        }
    }
```

**Comment by fuss86** [comment]
fine :)
